'use client';

import { useState, useEffect, useCallback } from 'react';
import { fetchNotionPages, writeToNotionPage, createProvenance } from '@/lib/api';
import { useChatStore } from '@/stores/chat-store';

interface SendToNotionProps {
  content: string;
  sessionId?: string;
  messageId?: string;
  /** Source model used to generate the content (e.g. 'gemini-2.5-flash') */
  sourceModel?: string;
}

/**
 * Compute a simple SHA-256 hex hash for provenance tracking.
 * Uses the Web Crypto API (available in modern browsers).
 */
async function sha256(text: string): Promise<string> {
  const encoder = new TextEncoder();
  const data = encoder.encode(text);
  const hashBuffer = await crypto.subtle.digest('SHA-256', data);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
}

export default function SendToNotion({ content, sessionId, messageId, sourceModel }: SendToNotionProps) {
  const [showPicker, setShowPicker] = useState(false);
  const [pages, setPages] = useState<any[]>([]);
  const [search, setSearch] = useState('');
  const [loading, setLoading] = useState(false);
  const [sending, setSending] = useState(false);
  const [sent, setSent] = useState<string | null>(null); // stores shortCode on success

  useEffect(() => {
    if (!showPicker) return;
    setLoading(true);
    fetchNotionPages().then(p => {
      setPages(p);
      setLoading(false);
    });
  }, [showPicker]);

  const handleSearch = useCallback(async (q: string) => {
    setSearch(q);
    setLoading(true);
    const p = await fetchNotionPages(q || undefined);
    setPages(p);
    setLoading(false);
  }, []);

  const handleSend = async (pageId: string, _pageTitle: string) => {
    setSending(true);
    try {
      // Step 1: Create a provenance record for traceability
      const contentHash = await sha256(content);
      let shortCode = '';

      try {
        const provenanceResult = await createProvenance({
          sourceType: 'native',
          sessionId: sessionId || undefined,
          messageId: messageId || `notion-write-${Date.now()}`,
          content,
          contentHash,
          sourceModel: sourceModel || 'synthesized',
        });
        shortCode = provenanceResult.shortCode || '';
      } catch (e) {
        console.warn('[SendToNotion] provenance creation failed, writing without ID:', e);
      }

      // Step 2: Build content with provenance footer
      const now = new Date();
      const dateStr = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')} ${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`;

      let contentWithProvenance = content;
      contentWithProvenance += '\n\n---\n';
      contentWithProvenance += `*Generated by Prism | ${dateStr}`;
      if (sourceModel) {
        contentWithProvenance += ` | Model: ${sourceModel}`;
      }
      if (sessionId) {
        contentWithProvenance += ` | Session: ${sessionId.slice(0, 8)}…`;
      }
      if (shortCode) {
        contentWithProvenance += ` | Provenance: ${shortCode}`;
      }
      contentWithProvenance += '*';

      // Step 3: Write to Notion with provenance-tagged content
      const result = await writeToNotionPage(pageId, contentWithProvenance, sessionId, messageId);

      if (result.ok) {
        setSent(shortCode || 'done');
        setShowPicker(false);
        setTimeout(() => setSent(null), 5000);
      }
    } catch (err) {
      console.error('[SendToNotion] write failed:', err);
    } finally {
      setSending(false);
    }
  };

  // Close on Escape
  useEffect(() => {
    if (!showPicker) return;
    const handler = (e: KeyboardEvent) => { if (e.key === 'Escape') setShowPicker(false); };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [showPicker]);

  return (
    <>
      <button
        onClick={() => setShowPicker(true)}
        className="inline-flex items-center gap-1 text-[10px] px-1.5 py-0.5 text-gray-500 hover:text-gray-300 transition-colors rounded hover:bg-gray-800/50"
        title="Send to Notion"
      >
        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <path d="M4 20h16a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.93a2 2 0 0 1-1.66-.9l-.82-1.2A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13c0 1.1.9 2 2 2Z" />
        </svg>
        {sent ? (
          sent !== 'done' ? (
            <>
              Sent!{' '}
              <span
                className="underline cursor-pointer hover:text-indigo-400"
                onClick={(e) => {
                  e.stopPropagation();
                  useChatStore.getState().lookupProvenance(sent);
                }}
                title="Click to view provenance details"
              >
                {sent}
              </span>
            </>
          ) : 'Sent!'
        ) : 'Notion'}
      </button>

      {showPicker && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60" onClick={() => setShowPicker(false)}>
          <div
            className="bg-gray-900 border border-gray-700 rounded-xl w-[400px] max-h-[450px] flex flex-col shadow-2xl"
            onClick={e => e.stopPropagation()}
          >
            <div className="flex items-center justify-between px-4 py-3 border-b border-gray-800">
              <h3 className="text-sm font-medium text-gray-200">Send to Notion</h3>
              <button onClick={() => setShowPicker(false)} className="text-gray-500 hover:text-gray-300 text-lg">✕</button>
            </div>

            <div className="px-4 py-2">
              <input
                type="text"
                value={search}
                onChange={e => handleSearch(e.target.value)}
                placeholder="Search pages..."
                autoFocus
                className="w-full px-3 py-1.5 text-sm bg-gray-800 border border-gray-700 rounded-lg text-gray-200 placeholder-gray-500 focus:outline-none focus:border-indigo-500"
              />
            </div>

            <div className="flex-1 overflow-y-auto px-2 pb-2 min-h-0">
              {loading ? (
                <div className="text-center text-gray-500 text-sm py-6">Loading...</div>
              ) : pages.length === 0 ? (
                <div className="text-center text-gray-500 text-sm py-6">No pages found</div>
              ) : (
                pages.map(page => (
                  <button
                    key={page.id}
                    onClick={() => handleSend(page.id, page.title)}
                    disabled={sending}
                    className="w-full text-left px-3 py-2 rounded-lg mb-0.5 hover:bg-gray-800/50 transition-colors flex items-center gap-2 disabled:opacity-50"
                  >
                    <span className="text-base flex-shrink-0">{page.iconEmoji || '📄'}</span>
                    <div className="flex-1 min-w-0">
                      <div className="text-sm text-gray-200 truncate">{page.title}</div>
                      <div className="text-[10px] text-gray-500">
                        {page.lastEditedAt ? new Date(page.lastEditedAt).toLocaleDateString() : ''}
                      </div>
                    </div>
                  </button>
                ))
              )}
            </div>

            {sending && (
              <div className="px-4 py-2 border-t border-gray-800 text-center text-xs text-indigo-400">
                Creating provenance record &amp; sending to Notion...
              </div>
            )}
          </div>
        </div>
      )}
    </>
  );
}
