import { Router, Request, Response } from 'express';
import { CompareRequest, MODELS } from '@prism/shared';
import { streamSingle, interleaveStreams, type ChatMessage } from '../services/llm-service';
import { saveMessage, getSessionMessages } from '../memory/conversation';
import { buildSessionContext } from '../memory/context-builder';
import { setupSSE, sseWrite } from './sse-utils';

const router = Router();

/**
 * POST /api/compare/stream
 *
 * Compare mode: send the origin model's latest response to critic models
 * for cross-evaluation. Streams all critiques back via SSE.
 *
 * Body: { sessionId, originModel, criticModels, instruction? }
 */
router.post('/stream', async (req: Request, res: Response) => {
  const { sessionId, originModel, criticModels, instruction }: CompareRequest = req.body;

  if (!sessionId || !originModel || !criticModels || criticModels.length === 0) {
    res.status(400).json({ error: 'sessionId, originModel, and criticModels[] are required' });
    return;
  }

  for (const model of [originModel, ...criticModels]) {
    if (!MODELS[model]) {
      res.status(400).json({ error: `Unknown model: ${model}` });
      return;
    }
  }

  // Find the origin model's latest assistant response in this session
  const messages = getSessionMessages(sessionId);
  const originResponses = messages.filter(
    (m) => m.role === 'assistant' && m.sourceModel === originModel
  );

  if (originResponses.length === 0) {
    res.status(400).json({ error: `No response from ${MODELS[originModel].displayName} found in this session` });
    return;
  }

  const latestOriginResponse = originResponses[originResponses.length - 1];
  const originDisplay = MODELS[originModel].displayName;

  // Set up SSE
  setupSSE(res);

  // Send metadata
  sseWrite(res, JSON.stringify({
    type: 'compare_start',
    originModel,
    originContent: latestOriginResponse.content,
    criticModels,
  }));

  // Build evaluation prompt for each critic
  const evalInstruction = instruction
    ?? 'Evaluate the following response. Identify strengths, weaknesses, factual errors, and areas for improvement. Be specific and constructive.';

  const criticStreams = criticModels.map((criticModel) => {
    // Build context for the critic model (token-budget-aware)
    const ctx = buildSessionContext(sessionId, criticModel);

    const criticMessages: ChatMessage[] = [
      ...ctx.messages,
      {
        role: 'user',
        content: [
          `The following response was generated by ${originDisplay}:`,
          '',
          '---',
          latestOriginResponse.content,
          '---',
          '',
          evalInstruction,
        ].join('\n'),
      },
    ];

    return streamSingle(criticModel, criticMessages);
  });

  // Stream all critiques interleaved
  const accumulated: Record<string, string> = {};

  try {
    for await (const chunk of interleaveStreams(criticStreams)) {
      const key = chunk.model;
      if (!accumulated[key]) accumulated[key] = '';
      accumulated[key] += chunk.content;

      sseWrite(res, JSON.stringify(chunk));
    }
  } catch (err: any) {
    sseWrite(res, JSON.stringify({ error: err.message }));
  }

  // Save critic responses (tagged as compare mode)
  for (const [model, content] of Object.entries(accumulated)) {
    if (content) {
      saveMessage(sessionId, 'assistant', content, model, { mode: 'compare' });
    }
  }

  // Fire-and-forget: auto-index session messages for RAG
  import('../services/rag-indexer').then(({ indexSessionMessages }) => {
    indexSessionMessages(sessionId).then((n) => {
      if (n > 0) console.log(`[compare/stream] RAG indexed ${n} chunks for session ${sessionId}`);
    }).catch((err) => {
      console.warn(`[compare/stream] RAG session indexing failed (non-critical):`, err.message);
    });
  }).catch(() => {});

  sseWrite(res, '[DONE]');
  res.end();
});

export default router;
